### PR TITLE
Add pry to gemfile

### PR DESCRIPTION
**Pull request by Se7enB2st**
Adding pry gem to development group

### CODE REVIEW

**Comment by chadbaum** [comment]
Pry-rails is the gem I was referring to that adds pry to the rails console.  Pry is just pry itself which you can install locally if you want.

See here:  https://github.com/rweng/pry-rails

**Comment by Se7enB2st** [comment]
Just update the gem to pry-rails, everything should be good now

**Comment by lasley** [comment]
LGTM 👍

**Comment by chadbaum** [comment]
:+1:

**Pull request merged**
