### PR TITLE
Continious integration and deployment

### PR DESCRIPTION
**Pull request by aleksgorbenko**
CodeShip CI pipeline is setup now. It is connected to our 'master' branch on Heroku, so whenever we push/merge to master on Github, Codeship should run all the tests automatically and if all are passed, the code will be deployed to Heroku.

I have also installed RSpec, factory_girl gems and made a simple test to pass, to make sure everything works. ['test' folder is now deleted]

Added CodeShip status badge to the readme file, so we will see the status of the latest master build.

### CODE REVIEW

**Comment by lasley** [comment]
This branch has conflicts that must be resolved before it can be merged to master. https://confluence.atlassian.com/bitbucket/resolve-merge-conflicts-704414003.html

**Comment by aleksgorbenko** [comment]
Alright, should be good to go now.

**Comment by lasley** [comment]
Simple enough 👍

**Comment by lasley** [comment]
FYI Coveralls is pretty cool though too - http://coveralls.io/

https://blog.codeship.com/codeship-code-coverage-coveralls/

**Comment by aleksgorbenko** [comment]
Ah nice! So its like test coverage visualised, I will set it up after this pull request is merged.

Will put it in the Backlog for now.

**Comment by lasley** [comment]
Yup exactly! It has a badge too, so you can easily see your test coverage.

Another cool one that I've recently started messing with is https://codeclimate.com/ - which identifies things like code repetition and other silliness.

**Comment by aleksgorbenko** [comment]
So you suggest using one or the other, or you kind of can use CodeClimate for code duplication only? 

The badges - basically yesterday the mystery how they are made was revealed to me :)

**Comment by lasley** [comment]
Typically I use all of them as they cover different aspects of the development cycle:
* Codeship covers the actual testing and deployment
* Coveralls consolidates analytics on what you tested and what you didn't
* CodeClimate consolidates the static analysis - which is things like code repetition, complexity, repetition.

There's also RuboCop, which I believe can actually feed information downstream to CodeClimate - https://github.com/bbatsov/rubocop

We don't need to do all in this case, I just like to show the options. Realistically RuboCop and CodeClimate will probably just slow everyone down because it enforces some best practices that take a long time to learn.

**Comment by aleksgorbenko** [comment]
Ok got it - thanks for the clarification. I have setup CodeShip to deploy to master branch on Heroku if all tests are passing (i hope that's alright?)

Ken also introduced the RuboCop as well, but if you say it will slow us down, perhaps we can apply it when we are almost done with the project? So the tool runs through the code and we just refactor it according to the best practices.

We will stick to Codeship and Coveralls for now then.

**Comment by lasley** [comment]
Yup RuboCop just analyzes the code against a Ruby style guide. It is one of those things that have to be added early or not at all though.

The person that applies it will have to go through and fix nearly every file in the code, so it's a bit of a PITA when there's an established codebase. For example, I can point out about 5-6 RuboCop errors in the code in this fairly simple PR. 

I recommend it because it will enforce some best practices you need to know for the workplace anyways. But then flip-side is the added complication. Makes it an on-the-fence recommendation for me.

**Pull request merged**
